name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/tms-backend/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/tms-backend
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::552823820846:role/TmsGitHubActionsRole
          aws-region: us-east-2

      - uses: aws-actions/setup-sam@v2

      - run: sam build

      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset