name: Frontend CI

on:
  pull_request:
    paths:
      - 'tms-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tms-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: https://6xytmkc6x6.execute-api.us-east-2.amazonaws.com/prod
          VITE_COGNITO_USER_POOL_ID: us-east-2_rHEVgHGnb
          VITE_COGNITO_USER_POOL_CLIENT_ID: osp77i6i8irqmhf1p8df3dlp7